# Generated by Django 4.0.3 on 2022-03-23 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='authot',
            new_name='author',
        ),
    ]
