# Generated by Django 4.0.3 on 2022-03-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
